AWSTemplateFormatVersion: '2010-09-09'
Description: Creates an IAM role for AWS CloudFormation to manage resources.
Resources:
  CloudFormationManagerRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: CloudFormationManagerRole
      Description: Role for AWS CloudFormation to manage resources.
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - cloudformation.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: '/'
      Policies:
        - PolicyName: CloudFormationFullAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'
Outputs:
  CloudFormationManagerRoleARN:
    Description: ARN of the IAM role created for CloudFormation
    Value: !GetAtt CloudFormationManagerRole.Arn

  CloudFormationManagerRoleName:
    Description: Name of the IAM role created for CloudFormation
    Value: !Ref CloudFormationManagerRole